#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

swww init &
swww img /home/aakodal/Documents/wallpapers/wallpaper.gif
systemctl --user start dunst &
redshift -PO 4600 -b 0.8:0.8 &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
/usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

/home/aakodal/.local/bin/eww open bar &
nm-applet &
nmcli device connect wlan0 &

dex -a -s ~/.config/hypr/autostart-desktops/ &
