#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

hyprpaper &
dunst &
redshift -PO 4600 -b 0.8:0.8 &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
/usr/lib/polkit-kde-authentification-agent-1 &
/usr/lib/polkit-gnome/polkit-gnome-authentification-agent-1 &

waybar &

dex -a -s ~/.config/hypr/autostart-desktops/ &
